# https://suyang.wiki/runbook/traefik/issue-certs.html

# 提供 Gzip 压缩
[http.middlewares.gzip.compress]

# 重定向到https
[http.middlewares.redirect-https.redirectScheme]
  scheme = "https"

# 定义一个空服务，用于一些特殊场景
[http.services]
  [http.services.noop.LoadBalancer]
     [[http.services.noop.LoadBalancer.servers]]
        url = "" # or url = "localhost"

# 定义一个简单的 BA 验证
[http.middlewares.common-auth.basicAuth]
  users = [
    # htpasswd -nb admin 123456
    "admin:$apr1$69CREdy6$Vurjfaly.stNnXTNndH2e0",
  ]
  removeheader = true
