version: '3.6'

services:

  gitea:
    image: ${GITEA_DOCKER_IMAGE}
    container_name: ${GITEA_SERVICE_DOMAIN}
    ports:
      - ${SSH_PORT_EXPOSE}:22
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - APP_NAME=${GITEA_SERVICE_NAME}
      - RUN_MODE=prod
      - RUN_USER=git
      - SSH_DOMAIN=${GITEA_SERVICE_DOMAIN}
      - SSH_PORT=22
      - SSH_LISTEN_PORT=22
      - HTTP_PORT=80
      - ROOT_URL=https://${GITEA_SERVICE_DOMAIN}
      - LFS_START_SERVER=true
      - REQUIRE_SIGNIN_VIEW=true
      - DB_TYPE=sqlite3
      - INSTALL_LOCK=false
      - DISABLE_GRAVATAR=true
    networks:
      - "traefik"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.giteaweb.entrypoints=http"
      - "traefik.http.routers.giteaweb.rule=Host(`${GITEA_SERVICE_DOMAIN}`)"
      - "traefik.http.routers.giteaweb.middlewares=redirect-https@file"
      - "traefik.http.routers.giteassl.entrypoints=https"
      - "traefik.http.routers.giteassl.rule=Host(`${GITEA_SERVICE_DOMAIN}`)"
      - "traefik.http.routers.giteassl.tls=true"
      - "traefik.http.routers.giteassl.middlewares=gzip@file"
      - "traefik.http.services.giteabackend.loadbalancer.server.scheme=http"
      - "traefik.http.services.giteabackend.loadbalancer.server.port=80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./repositories:/data/git/repositories"
      - "./data:/data/gitea/"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    extra_hosts:
      - "${GITEA_SERVICE_DOMAIN}:127.0.0.1"
    healthcheck:
      test: ["CMD-SHELL","wget -q --spider --proxy off localhost || exit 1"]
      interval: 5s

networks:
  traefik:
    external: true